import { VehicleConfig } from './types';

export const mx5Config: VehicleConfig = {
  APP_NAME: 'MX-5 Copilot',
  APP_SHORT_NAME: 'MX-5',
  APP_VERSION: '1.2.2',
  APP_TAGLINE: 'Passionné Mazda MX-5',
  BACKUP_FILENAME: 'mx5_copilot_backup.json',
  LOCATION_TASK_NAME: 'MX5_COPILOT_LOCATION_TRACKING',

  VEHICLE_PROFILE_IMAGE: require('../../../assets/vehicles/mx5/profile.png'),

  ASSETS: {
    icon: './assets/vehicles/mx5/icon.png',
    splash: './assets/vehicles/mx5/splash.png',
    adaptiveIcon: './assets/vehicles/mx5/adaptive-icon.png',
    favicon: './assets/vehicles/mx5/favicon.png',
  },

  BRAND_COLORS: {
    primary: '#D01C1F', // Mazda Red
    primaryDark: '#8B1214',
    accent: '#1F1F1F',
  },

  VEHICLE_MODELS: [
    'NA 1.6 (90ch)',
    'NA 1.6 (115ch)',
    'NA 1.8 (130ch)',
    'NB 1.6 (110ch)',
    'NB 1.8 (140ch)',
    'NBFL 1.6 (110ch)',
    'NBFL 1.8 (146ch)',
    'NC 1.8 (126ch)',
    'NC 2.0 (160ch)',
    'ND 1.5 (131ch)',
    'ND 2.0 (160ch)',
    'ND 2.0 (184ch)',
    'Mazdaspeed MX-5 Turbo',
  ],

  VEHICLE_YEARS: [
    '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
    '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
    '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
    '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024',
  ],

  ENGINE_TYPE_LABELS: {
    '4cyl': '4 Cylindres Atmosphérique',
    '6cyl': '2.0 / Version renforcée',
    'M': 'Mazdaspeed / Turbo',
  },

  detectEngineType: (model: string) => {
    const m = model.toLowerCase();
    if (m.includes('mazdaspeed') || m.includes('turbo')) return 'M';
    if (m.includes('2.0')) return '6cyl';
    return '4cyl';
  },

  MAINTENANCE_ITEMS: [
    { id: 'oil', label: 'Vidange + filtre à huile', typeLabel: 'Oil Service', category: 'maintenance', icon: 'droplets' },
    { id: 'air_filter', label: 'Filtre à air', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'wind' },
    { id: 'cabin_filter', label: 'Filtre habitacle', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'wind' },
    { id: 'ac_recharge', label: 'Recharge climatisation', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'thermometer' },
    { id: 'spark_plugs', label: 'Bougies', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'zap' },
    { id: 'fuel_filter', label: 'Filtre à essence', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'fuel' },
    { id: 'gearbox_oil', label: 'Huile boîte de vitesses', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'settings' },
    { id: 'differential_oil', label: 'Huile différentiel', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'settings' },
    { id: 'clutch', label: 'Embrayage', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'zap-off' },
    { id: 'accessory_belt', label: 'Courroie accessoires', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'refresh-ccw' },
    { id: 'pulleys', label: 'Galets (tendeurs + enrouleurs)', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'circle-dashed' },
    { id: 'brake_fluid', label: 'Liquide de frein', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'droplets' },
    { id: 'brake_pads_front', label: 'Plaquettes AV', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'brake_pads_rear', label: 'Plaquettes AR', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'brake_discs_front', label: 'Disques AV', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'brake_discs_rear', label: 'Disques AR', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'shocks', label: 'Amortisseurs', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'arrow-up-down' },
    { id: 'bushings', label: 'Silentblocs', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'layers' },
    { id: 'water_pump', label: 'Pompe à eau', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'refresh-cw' },
    { id: 'thermostat', label: 'Thermostat', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'thermometer' },
    { id: 'cooling_system', label: 'Radiateur + durites', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'shield-alert' },
    { id: 'coolant', label: 'Liquide refroidissement', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'droplets' },
    { id: 'timing', label: 'Courroie / chaîne distribution', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'settings' },
    { id: 'battery', label: 'Batterie', typeLabel: 'Entretien & réparation', category: 'other', icon: 'battery' },
    { id: 'tires_front', label: 'Pneus AV (avant)', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'circle' },
    { id: 'tires_rear', label: 'Pneus AR (arrière)', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'circle' },
    { id: 'soft_top', label: 'Entretien Capote', typeLabel: 'Entretien & réparation', category: 'other', icon: 'umbrella' },
  ],

  MAINTENANCE_SCHEMA: {
    '4cyl': {
      oil: { km: 10000, years: 1, detail: '5W30 ou 10W40 selon génération', cost: '60 – 120 €' },
      air_filter: { km: 20000, detail: 'Simple', cost: '20 – 50 €' },
      cabin_filter: { km: 20000, years: 2, detail: 'NC/ND surtout', cost: '25 – 70 €' },
      ac_recharge: { years: 3, detail: 'Selon usage', cost: '80 – 150 €' },
      spark_plugs: { km: 40000, detail: 'NGK / entretien courant', cost: '40 – 100 €' },
      fuel_filter: { km: 60000, detail: 'NA/NB surtout', cost: '30 – 80 €' },
      gearbox_oil: { km: 60000, detail: 'Boîte sensible à froid', cost: '60 – 120 €' },
      differential_oil: { km: 60000, detail: 'Pont arrière', cost: '50 – 100 €' },
      clutch: { km: 140000, detail: 'Usage normal', cost: '500 – 1 100 €' },
      accessory_belt: { km: 90000, years: 5, detail: 'Préventif', cost: '50 – 120 €' },
      pulleys: { km: 120000, detail: 'À surveiller avec courroie', cost: '80 – 250 €' },
      brake_fluid: { years: 2, detail: 'DOT 4', cost: '50 – 100 €' },
      brake_pads_front: { km: 40000, detail: 'Conduite loisir', cost: '80 – 180 €' },
      brake_pads_rear: { km: 60000, detail: 'Usure plus lente', cost: '70 – 160 €' },
      brake_discs_front: { km: 80000, detail: 'Selon usage', cost: '150 – 350 €' },
      brake_discs_rear: { km: 100000, detail: 'Moins sollicités', cost: '120 – 300 €' },
      shocks: { km: 100000, detail: 'Comportement routier', cost: '300 – 800 €' },
      bushings: { km: 120000, detail: 'Vieillissement trains roulants', cost: '250 – 700 €' },
      water_pump: { km: 100000, detail: 'Souvent avec distribution sur NA/NB', cost: '100 – 250 €' },
      thermostat: { km: 120000, detail: 'Préventif', cost: '80 – 180 €' },
      cooling_system: { km: 120000, detail: 'Radiateur et durites à surveiller', cost: '200 – 500 €' },
      coolant: { years: 2, detail: 'Important sur anciennes générations', cost: '40 – 90 €' },
      timing: { km: 100000, years: 5, detail: 'Courroie sur NA/NB, chaîne sur NC/ND 1.8 rare', cost: '300 – 700 €' },
      battery: { years: 5, detail: 'Petit gabarit selon version', cost: '80 – 180 €' },
      tires_front: { km: 30000, detail: 'Usure avant modérée', cost: '180 – 400 €' },
      tires_rear: { km: 25000, detail: 'Propulsion légère', cost: '180 – 400 €' },
      soft_top: { years: 1, detail: 'Imperméabilisation + nettoyage drains', cost: '30 – 100 €' },
    },

    '6cyl': {
      oil: { km: 10000, years: 1, detail: '5W30 synthèse', cost: '80 – 150 €' },
      air_filter: { km: 20000, detail: 'Moteur plus respirant', cost: '20 – 60 €' },
      cabin_filter: { km: 20000, years: 2, detail: 'Confort', cost: '25 – 70 €' },
      ac_recharge: { years: 3, detail: 'Selon usage', cost: '80 – 150 €' },
      spark_plugs: { km: 60000, detail: 'Bobines à surveiller', cost: '60 – 140 €' },
      fuel_filter: { km: 60000, detail: 'Entretien préventif', cost: '40 – 90 €' },
      gearbox_oil: { km: 60000, detail: 'Boîte 6 plus agréable vidangée', cost: '70 – 130 €' },
      differential_oil: { km: 60000, detail: 'Pont LSD selon version', cost: '50 – 120 €' },
      clutch: { km: 130000, detail: 'Couple supérieur', cost: '600 – 1 200 €' },
      accessory_belt: { km: 90000, years: 5, detail: 'Préventif', cost: '60 – 140 €' },
      pulleys: { km: 100000, detail: 'À surveiller', cost: '100 – 250 €' },
      brake_fluid: { years: 2, detail: 'Important', cost: '50 – 100 €' },
      brake_pads_front: { km: 35000, detail: 'Plus sollicité', cost: '100 – 220 €' },
      brake_pads_rear: { km: 50000, detail: 'Standard', cost: '80 – 180 €' },
      brake_discs_front: { km: 70000, detail: 'Plus sollicité', cost: '180 – 400 €' },
      brake_discs_rear: { km: 90000, detail: 'Standard', cost: '140 – 320 €' },
      shocks: { km: 90000, detail: 'Châssis plus ferme', cost: '350 – 900 €' },
      bushings: { km: 100000, detail: 'Silentblocs à surveiller', cost: '300 – 800 €' },
      water_pump: { km: 120000, detail: 'Préventif', cost: '120 – 280 €' },
      thermostat: { km: 120000, detail: 'Préventif', cost: '90 – 200 €' },
      cooling_system: { km: 120000, detail: 'Radiateur et vase selon génération', cost: '250 – 550 €' },
      coolant: { years: 4, detail: 'Long Life selon modèle', cost: '50 – 100 €' },
      timing: { km: 180000, detail: 'Chaîne sur NC/ND 2.0', cost: '0 – 900 €' },
      battery: { years: 5, detail: 'Équipements plus nombreux', cost: '100 – 220 €' },
      tires_front: { km: 28000, detail: 'Direction plus incisive', cost: '200 – 450 €' },
      tires_rear: { km: 22000, detail: 'Plus de couple', cost: '200 – 450 €' },
      soft_top: { years: 1, detail: 'Nettoyage drains et toile', cost: '30 – 100 €' },
    },

    'M': {
      oil: { km: 7000, years: 1, detail: 'Usage intensif / turbo', cost: '90 – 180 €' },
      air_filter: { km: 15000, detail: 'Admission plus sollicitée', cost: '25 – 70 €' },
      cabin_filter: { km: 20000, years: 2, detail: 'Confort', cost: '25 – 70 €' },
      ac_recharge: { years: 3, detail: 'Selon usage', cost: '80 – 150 €' },
      spark_plugs: { km: 30000, detail: 'Turbo / forte charge', cost: '60 – 140 €' },
      fuel_filter: { km: 50000, detail: 'Important', cost: '40 – 90 €' },
      gearbox_oil: { km: 50000, detail: 'Usage soutenu', cost: '70 – 130 €' },
      differential_oil: { km: 50000, detail: 'Pont plus sollicité', cost: '60 – 120 €' },
      clutch: { km: 100000, detail: 'Couple plus élevé', cost: '700 – 1 300 €' },
      accessory_belt: { km: 70000, years: 4, detail: 'Préventif', cost: '60 – 150 €' },
      pulleys: { km: 80000, detail: 'Usure plus rapide', cost: '100 – 280 €' },
      brake_fluid: { years: 2, detail: 'Conduite sportive', cost: '60 – 120 €' },
      brake_pads_front: { km: 25000, detail: 'Usage soutenu', cost: '120 – 250 €' },
      brake_pads_rear: { km: 35000, detail: 'Usage soutenu', cost: '90 – 200 €' },
      brake_discs_front: { km: 50000, detail: 'Freinage plus exigeant', cost: '220 – 450 €' },
      brake_discs_rear: { km: 70000, detail: 'Arrière', cost: '160 – 350 €' },
      shocks: { km: 70000, detail: 'Conduite dynamique', cost: '400 – 1 000 €' },
      bushings: { km: 80000, detail: 'À surveiller', cost: '350 – 900 €' },
      water_pump: { km: 100000, detail: 'Préventif', cost: '120 – 300 €' },
      thermostat: { km: 100000, detail: 'Gestion thermique turbo', cost: '100 – 220 €' },
      cooling_system: { km: 100000, detail: 'Refroidissement critique', cost: '250 – 600 €' },
      coolant: { years: 3, detail: 'Préventif', cost: '50 – 100 €' },
      timing: { km: 80000, years: 4, detail: 'Distribution / contrôle renforcé', cost: '400 – 900 €' },
      battery: { years: 4, detail: 'Usage loisir fréquent', cost: '100 – 220 €' },
      tires_front: { km: 22000, detail: 'Conduite sportive', cost: '220 – 500 €' },
      tires_rear: { km: 18000, detail: 'Propulsion + couple', cost: '220 – 500 €' },
      soft_top: { years: 1, detail: 'Entretien annuel', cost: '30 – 100 €' },
    },
  },

  HEALTH_STEPS_CONFIG: [
    {
      title: 'Moteur & lubrification',
      description: 'Fonctionnement interne du moteur et filtration.',
      enjeu: 'Longévité moteur + performances.',
      priority: 'Priorité élevée sur toutes les motorisations.',
      iconName: 'Activity',
      priorityLevel: 'high',
      itemIds: ['oil', 'spark_plugs', 'air_filter', 'timing', 'fuel_filter'],
    },
    {
      title: 'Système de refroidissement',
      description: 'Surveillance du circuit de refroidissement.',
      enjeu: 'Éviter la surchauffe moteur.',
      priority: 'Important sur les générations anciennes et usages soutenus.',
      iconName: 'Thermometer',
      priorityLevel: 'critical',
      itemIds: ['water_pump', 'thermostat', 'cooling_system', 'coolant'],
    },
    {
      title: 'Transmission & embrayage',
      description: 'Passage de puissance aux roues.',
      enjeu: 'Agrément de conduite + fiabilité.',
      priority: 'Important pour préserver la boîte et le pont.',
      iconName: 'ZapOff',
      priorityLevel: 'high',
      itemIds: ['gearbox_oil', 'differential_oil', 'clutch', 'accessory_belt', 'pulleys'],
    },
    {
      title: 'Trains roulants & suspension',
      description: 'Tenue de route et comportement.',
      enjeu: 'Stabilité, précision de conduite.',
      priority: 'Essentiel sur un roadster léger et précis.',
      iconName: 'Layers',
      priorityLevel: 'critical',
      itemIds: ['shocks', 'bushings'],
    },
    {
      title: 'Système de freinage',
      description: 'Sécurité avant tout.',
      enjeu: 'Sécurité.',
      priority: 'À ne jamais négliger.',
      iconName: 'Disc',
      priorityLevel: 'critical',
      itemIds: ['brake_fluid', 'brake_pads_front', 'brake_pads_rear', 'brake_discs_front', 'brake_discs_rear'],
    },
    {
      title: 'Confort & habitacle',
      description: 'Qualité de vie à bord.',
      enjeu: 'Confort, qualité de l’air.',
      priority: 'Moins critique mécaniquement.',
      iconName: 'Wind',
      priorityLevel: 'low',
      itemIds: ['cabin_filter', 'ac_recharge'],
    },
    {
      title: 'Électricité & énergie',
      description: 'Démarrage et alimentation.',
      enjeu: 'Fiabilité au quotidien.',
      priority: 'Important si voiture peu utilisée.',
      iconName: 'Battery',
      priorityLevel: 'high',
      itemIds: ['battery'],
    },
    {
      title: 'Pneumatiques',
      description: 'Liaison au sol.',
      enjeu: 'Sécurité + comportement routier.',
      priority: 'Impact direct sur le plaisir de conduite.',
      iconName: 'Circle',
      priorityLevel: 'critical',
      itemIds: ['tires_front', 'tires_rear'],
    },
    {
      title: 'Capote & Étanchéité',
      description: 'Entretien du toit souple et drains.',
      enjeu: 'Éviter infiltrations et corrosion.',
      priority: 'Spécifique cabriolet : très important.',
      iconName: 'Umbrella',
      priorityLevel: 'high',
      itemIds: ['soft_top'],
    },
  ],

  COMMUNITY_LINKS: [
    { name: 'MX5France', url: 'https://www.mx5france.com/' },
    { name: 'Passion MX-5', url: 'https://www.passion-mx5.com/' },
  ],

  LEGAL_TEXTS: {
    disclaimer: `MX-5 Copilot fournit des recommandations à titre indicatif. L'entretien et la sécurité du véhicule restent sous votre entière responsabilité.`,
    maintenanceDisclaimer: `Les intervalles sont donnés à titre indicatif selon les plans d'entretien standards. MX-5 Copilot ne se substitue pas à l'avis d'un professionnel.`,
    onboardingDisclaimer: `MX-5 Copilot est un outil d'assistance fourni à titre indicatif. `,
    onboardingBullets: [
      `Les données proviennent de retours d'expérience communautaire et non de documents constructeur officiels.`,
      `MX-5 Copilot ne remplace pas l'avis d'un professionnel.`,
      `Vous restez seul responsable de l'entretien et de la sécurité de votre véhicule.`,
    ],
    privacyIntro: `L'application MX-5 Copilot s'engage à respecter votre vie privée. Cette politique détaille comment nous traitons vos données.`,
    privacyStorage: `MX-5 Copilot est une application axée sur la confidentialité. La majorité des données que vous saisissez sont stockées uniquement sur votre appareil.`,
    legalNotice: `L'application MX-5 Copilot est un outil de suivi informatif. Les recommandations d'entretien, de remplacements de pièces et les échéances kilométriques fournies par l'application sont basées sur des principes généraux.`,
    legalNoSubstitute: `En aucun cas les informations de MX-5 Copilot ne peuvent se substituer à l'avis d'un professionnel qualifié, d'un mécanicien certifié ou aux préconisations officielles adaptées à l'état réel et précis de votre véhicule.`,
    legalAcceptance: `Ce document récapitule les termes juridiques acceptés lors de l'enregistrement initial de votre véhicule dans l'application. En poursuivant l'utilisation de MX-5 Copilot, vous maintenez votre accord avec ces conditions.`,
    pdfTitle: `Carnet d'Entretien - MX-5 Copilot`,
    pdfFooter: `© ${new Date().getFullYear()} MX-5 Copilot - Compagnon d'Entretien`,
  },

  GPS_CONFIG: {
    speedThreshold: 4.16,
    stopThreshold: 1.0,
    stopDuration: 300000,
    stationCheckInterval: 7200000,
    stationKeywords: [
      'Station', 'Total', 'Shell', 'Esso', 'BP', 'Avia', 'Eni', 'Relais',
      'Garage', 'Carrefour', 'Leclerc', 'Intermarché', 'Super U', 'Auchan'
    ],
    notifications: {
      tripEndTitle: "Trajet terminé 🚘",
      tripEndBody: (kms: number) => `Vous avez parcouru ${kms} km. Mettre à jour votre compteur ?`,
      stationTitle: "Station service détectée ⛽",
      stationBody: (name: string) => `${name || 'Une station'} a été détectée. Ajouter un plein ?`,
    },
  },

  BACKUP_TEXTS: {
    exportError: "Impossible d'exporter les données.",
    importError: "Le fichier de sauvegarde est corrompu ou invalide.",
    importInvalidFormat: "Format de fichier invalide",
    importConfirmTitle: "Restaurer la sauvegarde ?",
    importConfirmBody: "Cette action remplacera toutes vos données actuelles par celles du fichier de sauvegarde. Voulez-vous continuer ?",
    importSuccess: "Votre historique a été restauré avec succès.",
  },

  UI_TEXTS: {
    activeTripBanner: "Trajet Auto-Log en cours...",
    greeting: "Bonjour, Passionné",
    updateMileage: "Mettre à jour",
    optimalStatus: "Optimal",
    maintenanceStatus: "Entretien",
    lastLogs: "GPS Logs (50 derniers)",
    noLogs: "Aucun log enregistré pour le moment.",
    gpsLogsTitle: "GPS Logs",
    gpsDisabledTitle: "Auto-Log Désactivé",
    gpsDisabledBody: "Le suivi automatique est maintenant désactivé dans l'application. Pour une confidentialité totale, vous pouvez également révoquer l'accès à la position dans les réglages de votre iPhone.",
    iphoneSettings: "Réglages iPhone",
    logoutTitle: "Déconnexion",
    logoutConfirm: "Voulez-vous vraiment vous déconnecter ? Les données locales seront conservées.",
    cancel: "Annuler",
    errorTitle: "Erreur",
    pdfError: "Impossible de générer le document PDF.",
    logsError: "Impossible de lire les logs.",
  },
};