import { VehicleConfig } from './types';

export const z4Config: VehicleConfig = {
  APP_NAME: 'Z4 Copilot',
  APP_SHORT_NAME: 'Z4',
  APP_VERSION: '1.2.4',
  APP_TAGLINE: 'Passionné BMW Z4',
  BACKUP_FILENAME: 'z4_copilot_backup.json',
  LOCATION_TASK_NAME: 'Z4_COPILOT_LOCATION_TRACKING',

  VEHICLE_PROFILE_IMAGE: require('../../../assets/vehicles/z4/profile.png'),

  ASSETS: {
    icon: './assets/vehicles/z4/icon.png',
    splash: './assets/vehicles/z4/splash.png',
    adaptiveIcon: './assets/vehicles/z4/adaptive-icon.png',
    favicon: './assets/vehicles/z4/favicon.png',
  },

  BRAND_COLORS: {
    primary: '#003366',
    primaryDark: '#001A33',
    accent: '#E63946',
  },

  VEHICLE_MODELS: [
    'Roadster 2.0i (150ch)',
    'Roadster 2.2i (170ch)',
    'Roadster 2.5i (192ch)',
    'Roadster 2.5si (218ch)',
    'Roadster 3.0i (231ch)',
    'Roadster 3.0si (265ch)',
    'M Roadster (343ch)',
    'Coupé 3.0si (265ch)',
    'M Coupé (343ch)',
    'E89 sDrive18i (156ch)',
    'E89 sDrive20i (184ch)',
    'E89 sDrive23i (204ch)',
    'E89 sDrive28i (245ch)',
    'E89 sDrive30i (258ch)',
    'E89 sDrive35i (306ch)',
    'E89 sDrive35is (340ch)',
  ],

  VEHICLE_YEARS: [
    '2003', '2004', '2005', '2006', '2007', '2008', '2009',
    '2010', '2011', '2012', '2013', '2014', '2015', '2016',
  ],

  ENGINE_TYPE_LABELS: {
    '4cyl': '4 Cylindres (N46/N20)',
    '6cyl': '6 Cylindres (M54/N52/N54)',
    'M': 'Z4 M (S54)',
  },

  detectEngineType: (model: string) => {
    const m = model.toLowerCase();
    if (m.includes('m roadster') || m.includes('m coupé')) return 'M';
    if (m.includes('18i') || m.includes('20i') || m.includes('2.0')) return '4cyl';
    return '6cyl';
  },

  MAINTENANCE_ITEMS: [
    { id: 'oil', label: 'Vidange + filtre à huile', typeLabel: 'Oil Service', category: 'maintenance', icon: 'droplets' },
    { id: 'air_filter', label: 'Filtre à air', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'wind' },
    { id: 'cabin_filter', label: 'Filtre habitacle', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'wind' },
    { id: 'ac_recharge', label: 'Recharge climatisation', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'thermometer' },
    { id: 'spark_plugs', label: 'Bougies', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'zap' },
    { id: 'fuel_filter', label: 'Filtre à essence', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'fuel' },
    { id: 'gearbox_oil', label: 'Huile boîte de vitesses', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'settings' },
    { id: 'differential_oil', label: 'Huile différentiel', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'settings' },
    { id: 'clutch', label: 'Embrayage', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'zap-off' },
    { id: 'accessory_belt', label: 'Courroie accessoires', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'refresh-ccw' },
    { id: 'pulleys', label: 'Galets (tendeurs + enrouleurs)', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'circle-dashed' },
    { id: 'brake_fluid', label: 'Liquide de frein', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'droplets' },
    { id: 'brake_pads_front', label: 'Plaquettes AV', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'brake_pads_rear', label: 'Plaquettes AR', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'brake_discs_front', label: 'Disques AV', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'brake_discs_rear', label: 'Disques AR', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'disc' },
    { id: 'shocks', label: 'Amortisseurs', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'arrow-up-down' },
    { id: 'bushings', label: 'Silentblocs', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'layers' },
    { id: 'water_pump', label: 'Pompe à eau', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'refresh-cw' },
    { id: 'thermostat', label: 'Thermostat', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'thermometer' },
    { id: 'cooling_system', label: 'Radiateur + vase expansion', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'shield-alert' },
    { id: 'coolant', label: 'Liquide refroidissement', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'droplets' },
    { id: 'disa_valve', label: 'Valve DISA', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'settings' },
    { id: 'vanos_solenoids', label: 'Solénoïdes VANOS', typeLabel: 'Entretien & réparation', category: 'maintenance', icon: 'zap' },
    { id: 'soft_top_motor', label: 'Capote / moteur hydraulique', typeLabel: 'Entretien & réparation', category: 'other', icon: 'umbrella' },
    { id: 'battery', label: 'Batterie', typeLabel: 'Entretien & réparation', category: 'other', icon: 'battery' },
    { id: 'tires_front', label: 'Pneus AV (avant)', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'circle' },
    { id: 'tires_rear', label: 'Pneus AR (arrière)', typeLabel: 'Entretien & réparation', category: 'safety', icon: 'circle' },
  ],

  MAINTENANCE_SCHEMA: {
    '4cyl': {
      oil: { km: 12000, years: 1, detail: 'BMW LL-01 / LL-04', cost: '100 – 180 €' },
      air_filter: { km: 30000, detail: 'Entretien courant', cost: '30 – 60 €' },
      cabin_filter: { km: 30000, years: 2, detail: 'Charbon actif recommandé', cost: '40 – 90 €' },
      ac_recharge: { years: 3, detail: 'Perte naturelle de charge', cost: '80 – 150 €' },
      spark_plugs: { km: 60000, detail: '4 bougies', cost: '80 – 150 €' },
      fuel_filter: { km: 60000, detail: 'Selon version', cost: '80 – 150 €' },
      gearbox_oil: { km: 100000, detail: 'Préventif', cost: '100 – 250 €' },
      differential_oil: { km: 100000, detail: 'Pont arrière', cost: '100 – 200 €' },
      clutch: { km: 140000, detail: 'Usage normal', cost: '700 – 1 500 €' },
      accessory_belt: { km: 90000, years: 5, detail: 'Préventif', cost: '80 – 200 €' },
      pulleys: { km: 100000, detail: 'Bruits à surveiller', cost: '100 – 300 €' },
      brake_fluid: { years: 2, detail: 'DOT 4', cost: '80 – 150 €' },
      brake_pads_front: { km: 40000, detail: 'Freinage avant principal', cost: '120 – 250 €' },
      brake_pads_rear: { km: 60000, detail: 'Usure plus lente', cost: '100 – 200 €' },
      brake_discs_front: { km: 80000, detail: 'Ventilés selon version', cost: '200 – 500 €' },
      brake_discs_rear: { km: 100000, detail: 'Moins sollicités', cost: '150 – 400 €' },
      shocks: { km: 100000, detail: 'Confort et précision', cost: '400 – 900 €' },
      bushings: { km: 100000, detail: 'Vieillissement trains roulants', cost: '300 – 800 €' },
      water_pump: { km: 100000, detail: 'Préventif selon moteur', cost: '300 – 700 €' },
      thermostat: { km: 100000, detail: 'Avec pompe si possible', cost: '150 – 300 €' },
      cooling_system: { km: 120000, detail: 'Durites, vase, radiateur', cost: '400 – 800 €' },
      coolant: { years: 4, detail: 'Remplacement périodique', cost: '80 – 150 €' },
      battery: { years: 5, detail: 'Usage loisir / stockage', cost: '100 – 250 €' },
      tires_front: { km: 30000, detail: 'Selon conduite', cost: '200 – 500 €' },
      tires_rear: { km: 25000, detail: 'Propulsion', cost: '250 – 600 €' },
    },

    '6cyl': {
      oil: { km: 10000, years: 1, detail: 'Huile BMW LL-01', cost: '120 – 200 €' },
      air_filter: { km: 20000, detail: 'Plus sollicité', cost: '30 – 80 €' },
      cabin_filter: { km: 20000, years: 2, detail: 'Ventilation / confort', cost: '40 – 100 €' },
      ac_recharge: { years: 3, detail: 'Entretien courant', cost: '80 – 150 €' },
      spark_plugs: { km: 50000, detail: '6 bougies', cost: '120 – 220 €' },
      fuel_filter: { km: 50000, detail: 'Important sur usage régulier', cost: '80 – 150 €' },
      gearbox_oil: { km: 90000, detail: 'Préventif recommandé', cost: '100 – 250 €' },
      differential_oil: { km: 90000, detail: 'Couple plus élevé', cost: '100 – 200 €' },
      clutch: { km: 130000, detail: 'Plus sollicité', cost: '700 – 1 500 €' },
      accessory_belt: { km: 80000, years: 5, detail: 'Plus sollicitée', cost: '80 – 200 €' },
      pulleys: { km: 90000, detail: 'Usure plus rapide', cost: '100 – 300 €' },
      brake_fluid: { years: 2, detail: 'Important', cost: '80 – 150 €' },
      brake_pads_front: { km: 35000, detail: 'Freinage plus sollicité', cost: '120 – 250 €' },
      brake_pads_rear: { km: 50000, detail: 'Usure modérée', cost: '100 – 200 €' },
      brake_discs_front: { km: 70000, detail: 'Selon usage', cost: '200 – 500 €' },
      brake_discs_rear: { km: 90000, detail: 'Standard', cost: '150 – 400 €' },
      shocks: { km: 90000, detail: 'Tenue de route', cost: '400 – 900 €' },
      bushings: { km: 90000, detail: 'Point de vigilance BMW', cost: '300 – 800 €' },
      water_pump: { km: 90000, detail: 'Point sensible', cost: '400 – 900 €' },
      thermostat: { km: 100000, detail: 'Risque de surchauffe', cost: '150 – 300 €' },
      cooling_system: { km: 110000, detail: 'Fragilité BMW connue', cost: '400 – 800 €' },
      coolant: { years: 4, detail: 'Préventif', cost: '80 – 150 €' },
      disa_valve: { km: 100000, detail: 'Inspection / kit reconstruction', cost: '100 – 300 €' },
      vanos_solenoids: { km: 80000, detail: 'Nettoyage ou remplacement', cost: '150 – 400 €' },
      soft_top_motor: { years: 5, detail: 'Drainage capote E85', cost: '200 – 600 €' },
      battery: { years: 5, detail: '+ équipements', cost: '100 – 250 €' },
      tires_front: { km: 28000, detail: 'Direction précise', cost: '200 – 500 €' },
      tires_rear: { km: 20000, detail: 'Propulsion / couple', cost: '250 – 600 €' },
    },

    'M': {
      oil: { km: 8000, years: 1, detail: 'Huile premium, suivi rapproché', cost: '150 – 250 €' },
      air_filter: { km: 15000, detail: 'Usage sport', cost: '30 – 80 €' },
      cabin_filter: { km: 15000, years: 2, detail: 'Climatisation / habitacle', cost: '40 – 100 €' },
      ac_recharge: { years: 2, detail: 'Usage soutenu', cost: '80 – 150 €' },
      spark_plugs: { km: 40000, detail: 'Bougies spécifiques', cost: '150 – 300 €' },
      fuel_filter: { km: 40000, detail: 'À surveiller', cost: '80 – 150 €' },
      gearbox_oil: { km: 70000, detail: 'Conduite sportive', cost: '100 – 250 €' },
      differential_oil: { km: 70000, detail: 'Pont M / couple élevé', cost: '100 – 200 €' },
      clutch: { km: 100000, detail: 'Plus sollicité', cost: '700 – 1 500 €' },
      accessory_belt: { km: 70000, years: 4, detail: 'Préventif', cost: '80 – 200 €' },
      pulleys: { km: 80000, detail: 'Contrôle régulier', cost: '100 – 300 €' },
      brake_fluid: { years: 1, detail: 'Usage intensif', cost: '100 – 150 €' },
      brake_pads_front: { km: 30000, detail: 'Usage sport', cost: '120 – 250 €' },
      brake_pads_rear: { km: 40000, detail: 'Usage soutenu', cost: '100 – 200 €' },
      brake_discs_front: { km: 60000, detail: 'Freinage sportif', cost: '200 – 500 €' },
      brake_discs_rear: { km: 80000, detail: 'Freinage renforcé', cost: '150 – 400 €' },
      shocks: { km: 70000, detail: 'Comportement châssis', cost: '400 – 900 €' },
      bushings: { km: 70000, detail: 'Usure plus rapide', cost: '300 – 800 €' },
      water_pump: { km: 80000, detail: 'Critique', cost: '400 – 900 €' },
      thermostat: { km: 90000, detail: 'Surveillance élevée', cost: '150 – 300 €' },
      cooling_system: { km: 100000, detail: 'Circuit à surveiller', cost: '400 – 800 €' },
      coolant: { years: 3, detail: 'Préventif', cost: '80 – 150 €' },
      vanos_solenoids: { km: 60000, detail: 'Entretien spécifique', cost: '400 – 1200 €' },
      battery: { years: 4, detail: 'Équipements / stockage', cost: '100 – 250 €' },
      tires_front: { km: 25000, detail: 'Train avant très sollicité', cost: '200 – 500 €' },
      tires_rear: { km: 15000, detail: 'Couple élevé', cost: '250 – 600 €' },
    },
  },

  HEALTH_STEPS_CONFIG: [
    {
      title: 'Moteur & lubrification',
      description: 'Fonctionnement moteur et filtration.',
      enjeu: 'Longévité mécanique et performances.',
      priority: 'Priorité élevée sur toutes les motorisations.',
      iconName: 'Activity',
      priorityLevel: 'high',
      itemIds: ['oil', 'spark_plugs', 'air_filter', 'fuel_filter'],
    },
    {
      title: 'Admission & gestion moteur',
      description: 'Spécificités DISA et VANOS.',
      enjeu: 'Souplesse, rendement et fiabilité.',
      priority: 'Très important sur certaines motorisations BMW.',
      iconName: 'Settings',
      priorityLevel: 'high',
      itemIds: ['disa_valve', 'vanos_solenoids'],
    },
    {
      title: 'Système de refroidissement',
      description: 'Pompe, thermostat et circuit complet.',
      enjeu: 'Éviter la surchauffe moteur.',
      priority: 'Très important sur les motorisations BMW sensibles.',
      iconName: 'Thermometer',
      priorityLevel: 'critical',
      itemIds: ['water_pump', 'thermostat', 'cooling_system', 'coolant'],
    },
    {
      title: 'Transmission & embrayage',
      description: 'Boîte, pont et passage de puissance.',
      enjeu: 'Agrément et fiabilité de conduite.',
      priority: 'Plus sensible sur 6 cylindres et versions sportives.',
      iconName: 'ZapOff',
      priorityLevel: 'high',
      itemIds: ['gearbox_oil', 'differential_oil', 'clutch', 'accessory_belt', 'pulleys'],
    },
    {
      title: 'Trains roulants & suspension',
      description: 'Précision de conduite et stabilité.',
      enjeu: 'Tenue de route typique BMW roadster.',
      priority: 'Important avec l’âge du véhicule.',
      iconName: 'Layers',
      priorityLevel: 'high',
      itemIds: ['shocks', 'bushings'],
    },
    {
      title: 'Système de freinage',
      description: 'Endurance et sécurité.',
      enjeu: 'Sécurité active.',
      priority: 'À surveiller en permanence.',
      iconName: 'Disc',
      priorityLevel: 'critical',
      itemIds: ['brake_fluid', 'brake_pads_front', 'brake_pads_rear', 'brake_discs_front', 'brake_discs_rear'],
    },
    {
      title: 'Confort & habitacle',
      description: 'Climatisation et qualité de l’air.',
      enjeu: 'Confort d’utilisation.',
      priority: 'Moins critique mécaniquement.',
      iconName: 'Wind',
      priorityLevel: 'low',
      itemIds: ['cabin_filter', 'ac_recharge'],
    },
    {
      title: 'Capote & étanchéité',
      description: 'Protection du système de toit et drainage.',
      enjeu: 'Éviter l’humidité et les réparations coûteuses.',
      priority: 'Point important sur Z4 Roadster.',
      iconName: 'Umbrella',
      priorityLevel: 'high',
      itemIds: ['soft_top_motor'],
    },
    {
      title: 'Électricité & énergie',
      description: 'Démarrage et alimentation.',
      enjeu: 'Fiabilité au quotidien.',
      priority: 'Important si usage occasionnel.',
      iconName: 'Battery',
      priorityLevel: 'high',
      itemIds: ['battery'],
    },
    {
      title: 'Pneumatiques',
      description: 'Liaison au sol.',
      enjeu: 'Sécurité et comportement routier.',
      priority: 'Impact direct sur le plaisir de conduite.',
      iconName: 'Circle',
      priorityLevel: 'critical',
      itemIds: ['tires_front', 'tires_rear'],
    },
  ],

  COMMUNITY_LINKS: [
    { name: 'Z3-Z4 Club France', url: 'https://www.bmwz3club.fr/' },
    { name: 'ZPost (Global)', url: 'https://www.zpost.com/forums/' },
  ],

  LEGAL_TEXTS: {
    disclaimer: `Z4 Copilot fournit des recommandations à titre indicatif. L'entretien et la sécurité du véhicule restent sous votre entière responsabilité.`,
    maintenanceDisclaimer: `Les intervalles sont donnés à titre indicatif selon les usages et retours communautaires. Z4 Copilot ne se substitue pas à l'avis d'un professionnel.`,
    onboardingDisclaimer: `Z4 Copilot est un outil d'assistance fourni à titre indicatif.`,
    onboardingBullets: [
      `Données communautaires pour motorisations BMW N46, M54, N52, N20, N54 et S54.`,
      `Ne remplace pas le carnet constructeur ni un diagnostic professionnel.`,
      `L'utilisateur reste seul responsable de l'entretien de son véhicule.`,
    ],
    privacyIntro: `L'application Z4 Copilot respecte votre vie privée.`,
    privacyStorage: `Les données sont stockées localement sur votre appareil.`,
    legalNotice: `Outil de suivi informatif pour BMW Z4.`,
    legalNoSubstitute: `Ne remplace pas un mécanicien qualifié ni les préconisations constructeur.`,
    legalAcceptance: `L'utilisation de l'application vaut acceptation des conditions d'utilisation.`,
    pdfTitle: `Carnet d'Entretien - Z4 Copilot`,
    pdfFooter: `© ${new Date().getFullYear()} Z4 Copilot - Joy is BMW`,
  },

  GPS_CONFIG: {
    speedThreshold: 4.16,
    stopThreshold: 1.0,
    stopDuration: 300000,
    stationCheckInterval: 7200000,
    stationKeywords: ['Station', 'Total', 'Esso', 'Shell', 'BP', 'Avia', 'Eni'],
    notifications: {
      tripEndTitle: 'Trajet terminé 🏎️',
      tripEndBody: (kms: number) => `Votre Z4 a parcouru ${kms} km. Enregistrer le kilométrage ?`,
      stationTitle: 'Pause essence ? ⛽',
      stationBody: (name: string) => `${name || 'Une station'} détectée. Noter la dépense ?`,
    },
  },

  BACKUP_TEXTS: {
    exportError: 'Erreur lors de l’exportation Z4.',
    importError: 'Fichier Z4 corrompu ou invalide.',
    importInvalidFormat: 'Format Z4 non reconnu.',
    importConfirmTitle: 'Restaurer la sauvegarde Z4 ?',
    importConfirmBody: 'Cette action remplacera les données actuelles.',
    importSuccess: 'Restauration réussie.',
  },

  UI_TEXTS: {
    activeTripBanner: 'Trajet Auto-Log en cours...',
    greeting: 'Bonjour, Passionné BMW',
    updateMileage: 'Mettre à jour',
    optimalStatus: 'Optimal',
    maintenanceStatus: 'Entretien',
    lastLogs: 'Historique GPS',
    noLogs: 'Aucun trajet enregistré.',
    gpsLogsTitle: 'Trajets Z4',
    gpsDisabledTitle: 'Auto-Log désactivé',
    gpsDisabledBody: 'Le suivi automatique est désactivé dans l’application.',
    iphoneSettings: 'Réglages iPhone',
    logoutTitle: 'Déconnexion',
    logoutConfirm: 'Voulez-vous vraiment vous déconnecter ?',
    cancel: 'Annuler',
    errorTitle: 'Erreur',
    pdfError: 'Impossible de générer le PDF.',
    logsError: 'Impossible de lire les logs.',
  },
};